-- create a table to hold target standard claims.

create table if not exists std_med_claims (
CLAIM_NUMBER  VARCHAR2(50),
CLAIM_LINE_NUMBER  NUMBER,
CLAIM_TYPE  VARCHAR2(20),
PATIENT_ID  VARCHAR2(50),
SUBSCRIBER_ID  VARCHAR2(20),
ADMISSION_START_DATE  DATE,
ADMISSION_END_DATE  DATE,
DATE_OF_SERVICE  DATE,
DATE_OF_CLAIM_PAYMENT  DATE,
PLACE_OF_SERVICE  VARCHAR2(20),
DIAGNOSIS_CODE  VARCHAR2(20),
PROCEDURE_CODE  VARCHAR2(20),
REVENUE_CODE  VARCHAR2(20),
DRG_CODE  VARCHAR2(20),
TYPE_OF_BILL  VARCHAR2(3),
CLAIM_STATUS  VARCHAR2(1),
SERVICE_PROVIDER_ID  VARCHAR2(6),
SERVICE_PROVIDER_NAME  VARCHAR2(70),
SERVICE_PROVIDER_NPI  VARCHAR2(10),
SERVICE_QUANTITY  NUMBER,
NET_AMOUNT_PAID  NUMBER,
TOTAL_AMOUNT_BILLED  NUMBER,
AMOUNT_ALLOWED  NUMBER
);

-- source claims is already imported in the table source_claims

INSERT INTO STD_MED_CLAIMS

SELECT
TRIM(MC004) AS CLAIM_NUMBER,
TRIM(MC005) AS CLAIM_LINE_NUMBER,
TRIM(MC003) AS CLAIM_TYPE,
TRIM(MC010) AS PATIENT_ID,
NULL AS SUBSCRIBER_ID,
TRIM(MC018) AS ADMISSION_START_DATE,
TRIM(MC060) AS ADMISSION_END_DATE,
TRIM(MC059) AS DATE_OF_SERVICE,
TRIM(MC017) AS DATE_OF_CLAIM_PAYMENT,
TRIM(MC037) AS PLACE_OF_SERVICE,
TRIM(MC041) AS DIAGNOSIS_CODE,
TRIM(CASE WHEN MC036 IS NULL THEN MC055 ELSE MC058 END) AS PROCEDURE_CODE,
TRIM(MC054) AS REVENUE_CODE,
NULL AS DRG_CODE,
TRIM(MC036) AS TYPE_OF_BILL,
TRIM(MC038) AS CLAIM_STATUS,
TRIM(MC024) AS SERVICE_PROVIDER_ID,
NULL AS SERVICE_PROVIDER_NAME,
NULL AS SERVICE_PROVIDER_NPI,
TRIM(MC061) AS SERVICE_QUANTITY,
TRIM(MC063) AS NET_AMOUNT_PAID,
TRIM(MC062) AS TOTAL_AMOUNT_BILLED,
TRIM(MC062A) AS AMOUNT_ALLOWED
FROM source_claims;


